### ISSUE TITLE
[Auth] 학과 결정 정규식 & 구조 변경

### ISSUE THREAD

**Issue by ChoiWonBeen** [BCSDLab/KOIN_WEB#201]
충격적이게도 우리가 알던것과 학번의 구조가 달랐습니다

<img width="702" alt="image" src="https://user-images.githubusercontent.com/50780281/189522992-50399b1f-f5f9-4be6-a0dd-eb31df72fabf.png">

_**여기에 대학원생과 외국인학생은 학번 구조가 또 다릅니다. (총 8자리)**_

- 현재 디자인+건축을 151번이라고 인식중이었는데, 건축은 72번으로 다른 학과번호를 가졌습니다. (유효한 학번이 아니라고 처리)
- 백엔드 API 스키마의 도메인이 수정되어야하므로 백엔드 배포 후 배포할 수 있도록 hotfix가 아닌, Develop브랜치에 추가해주어야합니다. (버스와 동시 배포 예정)
- 8자 학번, 석사 등이 DB도메인에 포함될지는 백엔드 담당자와 의논이 필요할 것 같습니다.
- +`major`라는 필드를 optional로 담아서 주는데, 필요할지도 의논하면 좋을 것 같습니다.

지난번에도 학번 관리에 문제가 있었으니, 로직과 구조 자체에 대한 개선이 필요해보입니다.

**Comment by knight7024** [comment]
http://rule.koreatech.ac.kr/service/law/lawFullScreen.do?seq=60&historySeq=636&key=%25ED%2595%2599%25EC%2582%25AC

**Comment by knight7024** [comment]
또한 대학원생과 유학생들의 학번은 규칙을 모르기 때문에 당분간 해결 불가능

기존의 코인 소스들도 학번을 10자리로 검증하는 것으로 보아할 때 기획에 제외되어 있던 것은 아닌가 생각함.
